---
silviop:
  NAMESPACE: "workshop-silviop"
  NAMESPACE_DISPLAY_NAME: "Workshops SILVIOP"
  USER: "silviop"
samuelvl:
  NAMESPACE: "workshop-samuelvl"
  NAMESPACE_DISPLAY_NAME: "Workshops SAMUELVL"
  USER: "samuelvl"

ansible_connection: local
openshift_cluster_content:
- object: projectrequest
  content:
  - name: "silviop"
    template: "/home/silvio/workshopitx/ocp4-workshop-objects-generator/templates/project-requests.yml"
    action: create
    params_from_vars: "{{ silviop }}"
    tags:
    - projects
- object: projectrequest
  content:
  - name: "samuelvl"
    template: "/home/silvio/workshopitx/ocp4-workshop-objects-generator/templates/project-requests.yml"
    action: create
    params_from_vars: "{{ samuelvl }}"
    tags:
    - projects
