---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gogs
  labels:
    app: workshop-gogs
    env: workshop
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 250Mi 
  storageClassName: ${GOGS_STORAGE_CLASS_NAME}
...