kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gogs
  env: workshop
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 250Mi 
  storageClassName: $STORAGE_CLASS_NAME_GOGS
