---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example-pod-shared
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: helper8.docp4.lab.bcnconsulting.com
    path: /var/nfsshare/wksp-pod-shared
---    
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvclaim-example-pod-shared
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
  volumeName: pv-example-pod-shared   
...          