---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod-secret
  labels:
    app: workshop-pod-secret-example
    env: workshop 
spec:
  containers:
    - name: container-one
      image: ${EXTERNAL_REGISTRY}/${POSTGRES_IMAGE}
      env:
      - name: POSTGRESQL_USER
        value: gogs
      - name: POSTGRESQL_DATABASE
        value: gogs
      - name: POSTGRESQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-password
            key: password   
      ports:
        - name: postgres-port 
          containerPort: 5432
  restartPolicy: Always
...
