---
apiVersion: v1
kind: Service
metadata:
  name: hostname-postgres
  labels:
    app: workshop-postgres
    env: workshop
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: workshop-postgres
...  